_target_: core.module.codeformer_module.CodeFormerTrainer
defaults:
  - _self_
  - dataset: face_dataset
  - model: codeformer
  - elsemodel: vqgan
  - loss: ce

w: 1

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-2
  weight_decay: 0


batch_size: 2
num_workers: 4