hydra:
  run:
    dir: logs/hydra_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - module: diffbir_stage2

Trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: "gpu"
  devices: "1"
  precision: 32