_target_: model.codeformer.codeformer.CodeFormer
dim_embd: 512
n_head: 8
n_layers: 9
codebook_size: 1024
connect_list: ['32', '64', '128', '256']
fix_modules: ['quantize','generator']
vqgan_path: /workspace/zlatkd12/mok/FaceVidSR/src/external/CodeFormer/experiments/pretrained_models/vqgan/vqgan_code1024.pth # pretrained VQGAN 